security:
    enable_authenticator_manager: true
    password_hashers:
        App\Entity\Utilisateur: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator:
                - App\Security\GoogleAuthenticator
                - App\Security\LoginFormAuthenticator
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                username_parameter: email
                password_parameter: password
                success_handler: App\Security\LoginSuccessHandler
                failure_handler: App\Security\LoginFailureHandler
            logout:
                path: app_logout
                target: app_login

    role_hierarchy:
        ROLE_USER: []
        ROLE_CLIENT: ROLE_USER
        ROLE_ARTISAN: ROLE_USER
        ROLE_CONSTRUCTEUR: ROLE_USER
        ROLE_ADMIN: [ROLE_CLIENT, ROLE_CONSTRUCTEUR, ROLE_ARTISAN]

    access_control:
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/welcome, roles: ROLE_USER }
        - { path: ^/tache, roles: ROLE_CONSTRUCTEUR }
        - { path: ^/plannification, roles: ROLE_USER }