twig:

    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    number_format:
        decimals: 2
        decimal_point: ','
        thousands_separator: ' '
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        # Your existing globals here (if any)
    paths:
        '%kernel.project_dir%/templates/bundles/MaterialDashboard': MaterialDashboard

when@test:
    twig:
        strict_variables: true
