controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# config/routes.yaml
app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: [GET, POST]

app_login:
    path: /login
    controller: App\Controller\LoginController::index
    methods: [GET, POST]

app_logout:
    path: /logout

app_welcome:
    path: /welcome
    controller: App\Controller\WelcomeController::index
    
app_home:
    path: /
    controller: App\Controller\HomeController::index

app_face_upload:
    path: /face-upload/{id}
    controller: App\Controller\RegistrationController::faceUpload
    requirements:
        id: \d+

app_save_face:
    path: /save-face/{id}
    controller: App\Controller\RegistrationController::saveFace
    methods: POST
    requirements:
        id: \d+    
        
        