# config/services.yaml

parameters:
    photos_directory: '%kernel.project_dir%/public/uploads/photos'
    uploads_directory: '%kernel.project_dir%/public/uploads'
    gemini.api_key: '%env(GEMINI_API_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Symfony\Contracts\HttpClient\HttpClientInterface: '@http_client'

    App\Service\GeminiService:
        arguments:
            $geminiApiKey: '%gemini.api_key%'

framework:
    http_client:
        default_options:
            max_duration: 30