# config/services.yaml

parameters:
    photos_directory: '%kernel.project_dir%/public/uploads/photos'
    uploads_directory: '%kernel.project_dir%/public/uploads'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $googleClientId: '%env(GOOGLE_CLIENT_ID)%'
            string $googleClientSecret: '%env(GOOGLE_CLIENT_SECRET)%'
            string $googleRedirectUri: '%env(GOOGLE_REDIRECT_URI)%'
            string $html2pdfApiKey: '%env(HTML2PDF_API_KEY)%'

            # ... other binds
            
    

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Security/GoogleAuthenticator.php'

    App\Security\GoogleAuthenticator:
        arguments:
            $router: '@router'
            $entityManager: '@doctrine.orm.entity_manager'
            $passwordHasher: '@security.user_password_hasher'
            $loginSuccessHandler: '@App\Security\LoginSuccessHandler'

    App\Security\LoginSuccessHandler: ~

    App\Security\LoginFailureHandler:
        arguments:
            $router: '@router'

    Symfony\Contracts\HttpClient\HttpClientInterface: '@http_client'

    App\Security\CustomUserProvider:
        arguments:
            $connection: '@doctrine.dbal.default_connection'

    App\Repository\CustomReclamationRepository:
        arguments:
            $connection: '@doctrine.dbal.default_connection'

    App\Repository\CustomUtilisateurRepository:
        arguments:
            $connection: '@doctrine.dbal.default_connection'
            $passwordHasher: '@security.user_password_hasher'

   

    App\Service\HtmlToPdfService:
        arguments:
            $httpClient: '@http_client'
            $apiKey: '%env(HTML2PDF_API_KEY)%'